spring:
  application:
    name: instazoo

  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    # Ищет переменную окружения JWT_EXPIRATION, если её нет — берет 600000
    expiration-time: ${JWT_EXPIRATION:600000}
